class BoardClass {
  board_items = [
    {
      id: 22,
      title: '가장 최근의 22 번째 게시글',
      userId: 'userId-4',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 21,
      title: '21 번째 게시글',
      userId: 'userId',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    { 
      id: 20,
      title: '20 번째 게시글',
      userId: 'userId-2',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 19,
      title: '19 번째 게시글',
      userId: 'userId-3',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 18,
      title: '18 번째 게시글',
      userId: 'userId-4',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 17,
      title: '17 번째 게시글',
      userId: 'userId',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    { 
      id: 16,
      title: '16 번째 게시글',
      userId: 'userId-2',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 15,
      title: '15 번째 게시글',
      userId: 'userId-3',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 14,
      title: '14 번째 게시글',
      userId: 'userId-4',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 13,
      title: '13 번째 게시글',
      userId: 'userId-3',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 12,
      title: '가장 최근의 12 번째 게시글',
      userId: 'userId-4',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 11,
      title: '11 번째 게시글',
      userId: 'userId',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    { 
      id: 10,
      title: '10 번째 게시글',
      userId: 'userId-2',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 9,
      title: '9 번째 게시글',
      userId: 'userId-3',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 8,
      title: '8 번째 게시글',
      userId: 'userId-4',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 7,
      title: '7 번째 게시글',
      userId: 'userId',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    { 
      id: 6,
      title: '6 번째 게시글',
      userId: 'userId-2',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 5,
      title: '5 번째 게시글',
      userId: 'userId-3',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 4,
      title: '4 번째 게시글',
      userId: 'userId-4',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 3,
      title: '3 번째 게시글',
      userId: 'userId-3',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 2,
      title: '2 번째 게시글',
      userId: 'userId-4',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
    {
      id: 1,
      title: '1 번째 게시글',
      userId: 'userId-4',
      createdAt: '2021-08-11',
      supervisor: false,
      content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolor quis vero praesentium, adipisci enim asperiores, animi officia ipsam qui magni vitae doloribus architecto non molestias quam itaque provident eaque!',
    },
  ]

  add_board (item) {
    this.board_items.unshift(item);
  }

  get_board() {
    return this.board_items;
  }
}

export default BoardClass;